version: '3'
services:
  mudlib:  
    restart: unless-stopped
    build: ./fluffos
    image: kaiserli/mudlib:v1
    ports:
    - "48555:5555"
    command:
    - "/fluffos/mudlib/config.es2"
    volumes:
    - "./mudlib:/fluffos/mudlib"
    - "./data:/fluffos/mudlib/data"
    - "./log:/fluffos/mudlib/log"    
  
  webmud:
    restart: unless-stopped
    build: ./webmud
    image: kaiserli/webmud:v1
    ports:
    - "48080:8080"
    command:
    - "./main.js"
    - "8080"
    - "5555"
    - "-w"
    - "./www"
    - "-h"
    - "mudlib"
    - "-m" 
    - "/mudlib"
    volumes:
    - "./www:/webmud/www"
    - "./mudlib:/mudlib"